version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sillicon
      POSTGRES_DB: hrms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  hrms-api:
    image: hrms-api:1.0
    container_name: hrms_api_container
    ports:
      - "8089:8089"

volumes:
  postgres_data: